plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.115'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()

    maven {
        url = 'https://maven.blamejared.com/'
        content {
            includeGroup 'com.hollingsworth'
            includeGroup 'com.hollingsworth.arsnouveau'
        }
    }

    maven {
        url = 'https://cursemaven.com/'
        content {
            includeGroup 'curse.maven'
        }
    }

    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.parchment_version
        minecraftVersion = project.parchment_minecraft
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "com.hollingsworth.arsnouveau:ars_nouveau-${minecraft_version}:${ars_nouveau_version}"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        minecraft_version   : minecraft_version, minecraft_version_range: '[1.21.1,)',
        neo_version         : neoforge_version, neo_version_range: '[21.0.109,)',
        loader_version_range: '[4,)',
        mod_id              : mod_id, mod_name: mod_name, mod_license: 'MIT',
        mod_version         : mod_version, mod_authors: mod_authors,
        mod_description     : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
